# Generated by Django 4.2.5 on 2023-10-11 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("new", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="room",
            name="participant",
            field=models.ManyToManyField(
                blank=True, related_name="Participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
